package PersonalProject.demo.Enums;

public enum UserRole {
    ROLE_SUPER_ADMIN,
    ROLE_ADMIN,
    ROLE_STORE_MANAGER,
    ROLE_BRANCH_MANAGER,
    ROLE_INVENTORY_MANAGER,
    ROLE_CASHIER,
    ROLE_EMPLOYEE,
    ROLE_CUSTOMER,
    ROLE_SECURITY_GUARD
}
